// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA77C9miymNdG3uFqPqMCqQPNrTRbf16w',
    appId: '1:531466222390:web:ecf6bf7f36069d13841197',
    messagingSenderId: '531466222390',
    projectId: 'pmobile-18699',
    authDomain: 'pmobile-18699.firebaseapp.com',
    storageBucket: 'pmobile-18699.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ45-m1ORkQ1nCER9oU_K3hd9HSSi-cj4',
    appId: '1:531466222390:android:2c9c35ca70db5d67841197',
    messagingSenderId: '531466222390',
    projectId: 'pmobile-18699',
    storageBucket: 'pmobile-18699.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIlJvGc0HP9prfouVGqBDXVFBn-n4sgzM',
    appId: '1:531466222390:ios:c5a2631c8e89b945841197',
    messagingSenderId: '531466222390',
    projectId: 'pmobile-18699',
    storageBucket: 'pmobile-18699.appspot.com',
    iosBundleId: 'com.example.uasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIlJvGc0HP9prfouVGqBDXVFBn-n4sgzM',
    appId: '1:531466222390:ios:3feab42c2bda338e841197',
    messagingSenderId: '531466222390',
    projectId: 'pmobile-18699',
    storageBucket: 'pmobile-18699.appspot.com',
    iosBundleId: 'com.example.uasApp.RunnerTests',
  );
}
